import 'package:emulator_guard/methods/android/android.dart';

final allAndroidMethods = [
  AvailableRamMethod(),
  BlueStacksDetectionMethod(),
  BoardEmulatorMethod(),
  BootloaderMethod(),
  BrandModelMismatchMethod(),
  BuildTypeMethod(),
  DeviceEmulatorMethod(),
  EmulatorFilesMethod(),
  FingerprintCIMethod(),
  FingerprintDevKeysMethod(),
  FreeDiskSpaceMethod(),
  HardwareEmulatorMethod(),
  HardwareX86Method(),
  HostCIMethod(),
  HostJenkinsMethod(),
  IsEmulatorMethod(),
  LDPlayerDetectionMethod(),
  ManufacturerUnknownMethod(),
  MEmuDetectionMethod(),
  ModelCpuMismatchMethod(),
  ModelEmulatorMethod(),
  PixelFeaturesMethod(),
  ProductEmulatorMethod(),
  SerialNumberMethod(),
  SystemFeaturesEmptyMethod(),
];
